### ISSUE TITLE
Coverage script does not work

### ISSUE THREAD

**Issue by Daguerreo** [kelvins/CodeCoverageExampleQt#1]
Files in coverage.info are for your local machine:

`SF:/Users/kelvinsp/Qt5.3.2/5.3/clang_64/lib/QtCore.framework/Headers/qatomic_x86.h`

so script obviously does not work

**Comment by kelvins** [comment]
Hello @Daguerreo, this is not a project to be used as is.

This is the final result of the step-by-step explained in the following Medium story.

https://medium.com/@kelvin_sp/generating-code-coverage-with-qt-5-and-gcov-on-mac-os-4999857f4676

The `coverage.info` file is automatically generated, if you follow the correct steps and build it in your machine it will have the correct path.

**Comment by Daguerreo** [comment]
> Hello @Daguerreo, this is not a project to be used as is.
> 
> This is the final result of the step-by-step explained in the following Medium story.
> 
> https://medium.com/@kelvin_sp/generating-code-coverage-with-qt-5-and-gcov-on-mac-os-4999857f4676
> 
> The `coverage.info` file is automatically generated, if you follow the correct steps and build it in your machine it will have the correct path.

I know that, but I mean, what's the point in publishing a script which works only in your machine? The aim of a tutorial should be the repeatability not the "ehy look, that worked on my laptop!" if you understand what I mean. :)

**Comment by kelvins** [comment]
I understood what you mean but seems you are mixing things up.

If you actually follow the tutorial step-by-step (on Medium) you will see I'm not using any absolute path, so it should not be a problem. As far as I know the tutorial is easily repeatable and must work in any machine with dependencies correctly installed.

In the `runCoverage.sh` script there is a note saying to edit the paths as needed (but the paths are relative to the `dirname`):

https://github.com/kelvins/CodeCoverageExampleQt/blob/1f36c5c5577b25c9d002c9c1af58cd179c9633ae/CodeCoverageExample/scripts/runCoverage.sh#L3-L14

The `coverage.info` file you mentioned was automatically generated, if you generate it in your machine (what you should do), it will have your absolute paths.

The objective of the project on Github is not to be executable, is to be used as a reference to the tutorial (including the files generated by it). The main idea is to follow the entire tutorial step-by-step and understand how to apply it in your own projects. If even so you want to skip the tutorial and build the project as is, you need to re-generate the coverage files by yourself.
